### ISSUE TITLE
 unrecognized arguments

### ISSUE THREAD

**Issue by katesaikishore** [SemyonMakhaev/dns-poison#1]
poison.py: error: unrecognized arguments

When I was typing the address flag then it shows the above error!
Please help me in this

**Comment by katesaikishore** [comment]
And I have given 3fields 
Server  IP Address
Name   Domain Name Of my server
Address IP Address of my server

**Comment by katesaikishore** [comment]
Hey Sorry I figured it out but btw I am getting no response but a blank cursor?

**Comment by SemyonMakhaev** [comment]
> Hey Sorry I figured it out but btw I am getting no response but a blank cursor?

Hi!

Actually this is expected situation if you try to poison a  **real** server. The program tries to get ahead of a real forwarder when it sends DNS-replies. However the probability of this event is obviously small.

The main reason is that an architecture of a real DNS-forwarder allows it to send a reply more quickly than the program. In addition the program sends DNS-reply to all of server ports trying to predict a port where server waits an answer from its forwarder. But a real forwarder sends only one reply and doesn't waste time to find a port.

But if you try many-many times maybe you'll be lucky 😅 

So if you'd like to study the DNS-poison vulnerability you can code a simple caching DNS-server with artificial delays or using any particular port and the program will be able to poison it.

**Comment by katesaikishore** [comment]
Thank You for your reply bro! And thanks for a detailed reply! I was helpful with that😊

**Comment by SemyonMakhaev** [comment]
Cheers!

**Comment by katesaikishore** [comment]
Hey I have doubts in this! I dont wanna spam the github on your project!

Can you give your whatsapp number
Or facebook id?

Thank You bro

**Comment by SemyonMakhaev** [comment]
> Hey I have doubts in this! I dont wanna spam the github on your project! Can you give your whatsapp number Or facebook id? Thank You bro

On your email
